--- #YAML:1.0
name:               Getopt-Valid
version:            v0.1.0
abstract:           Getopt implementation with extended validation
author:
    - Ulrich Kautz <uk@fortrabbit.e>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Spec:    0
    Getopt::Long:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
